name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Set up environment variables
        env:
          COURSE_ID: ${{ secrets.COURSE_ID }}
          HIVEMQ_HOST: ${{ secrets.HIVEMQ_HOST }}
          HIVEMQ_USERNAME: ${{ secrets.HIVEMQ_USERNAME }}
          HIVEMQ_PASSWORD: ${{ secrets.HIVEMQ_PASSWORD }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        run: |
          echo "Setting up environment variables..."
          
      - name: Run tests
        env:
          COURSE_ID: ${{ secrets.COURSE_ID }}
          HIVEMQ_HOST: ${{ secrets.HIVEMQ_HOST }}
          HIVEMQ_USERNAME: ${{ secrets.HIVEMQ_USERNAME }}
          HIVEMQ_PASSWORD: ${{ secrets.HIVEMQ_PASSWORD }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        run: |
          pytest

      - name: Autograding
        uses: education/autograding@v1