name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Create file for setting env vars
        run: |
          echo "#!/bin/sh" > setenv.sh
          echo "export COURSE_ID=\"${{ secrets.COURSE_ID }}\"" >> setenv.sh
          echo "export HIVEMQ_HOST=\"${{ secrets.HIVEMQ_HOST }}\"" >> setenv.sh
          echo "export HIVEMQ_PASSWORD=\"${{ secrets.HIVEMQ_PASSWORD }}\"" >> setenv.sh
          echo "export HIVEMQ_USERNAME=\"${{ secrets.HIVEMQ_USERNAME }}\"" >> setenv.sh
          echo "export DATABASE_NAME=\"${{ secrets.DATABASE_NAME }}\"" >> setenv.sh
          echo "export COLLECTION_NAME=\"${{ secrets.COLLECTION_NAME }}\"" >> setenv.sh
          echo "export CLUSTER_NAME=\"${{ secrets.CLUSTER_NAME }}\"" >> setenv.sh
          echo "export AWS_ACCESS_KEY_ID=\"${{ secrets.AWS_ACCESS_KEY_ID }}\"" >> setenv.sh
          echo "export AWS_SECRET_ACCESS_KEY=\"${{ secrets.AWS_SECRET_ACCESS_KEY }}\"" >> setenv.sh
          echo "export AWS_REGION=\"${{ secrets.AWS_REGION }}\"" >> setenv.sh
          echo "export DYNAMODB_TABLE_NAME=\"${{ secrets.DYNAMODB_TABLE_NAME }}\"" >> setenv.sh
          echo "export CONNECTION_STRING=\"${{ secrets.CONNECTION_STRING }}\"
          echo "export CONNECTION_STRING=\"${{ secrets.CONNECTION_STRING }}\"" >> setenv.sh
      - uses: education/autograding@v1
        env:
          COURSE_ID: ${{ secrets.COURSE_ID }}
          HIVEMQ_HOST: ${{ secrets.HIVEMQ_HOST }}
          HIVEMQ_PASSWORD: ${{ secrets.HIVEMQ_PASSWORD }}
          HIVEMQ_USERNAME: ${{ secrets.HIVEMQ_USERNAME }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DYNAMODB_TABLE_NAME: ${{ secrets.DYNAMODB_TABLE_NAME }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}